# kindle_dict\docker\Dockerfile.dev

FROM python:3.11-slim

# Ustawienie zmiennych środowiskowych
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Dodanie architektury i386 dla obsługi aplikacji 32-bitowych
RUN dpkg --add-architecture i386

# Instalacja wine do uruchamiania kindlegen.exe wraz z zależnościami 32-bitowymi
RUN apt-get update && apt-get install -y --no-install-recommends \
    wine \
    wine32 \
    wine64 \
    libwine \
    libwine:i386 \
    fonts-wine \
    default-libmysqlclient-dev \
    build-essential \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Ustawienie katalogu roboczego
WORKDIR /app

# Kopiowanie i instalacja zależności
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Kopiowanie projektu
COPY ./src /app/

# Tworzenie użytkownika nieroot
RUN useradd --create-home appuser
RUN chown -R appuser:appuser /app
USER appuser

# Uruchomienie serwera deweloperskiego
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]