# Generated by Django 4.2.10 on 2025-03-15 06:31

import dictionary.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('language_code', models.CharField(default='pl', max_length=10, verbose_name='Language Code')),
                ('creator_name', models.CharField(max_length=255, verbose_name='Creator Name')),
                ('build_version', models.PositiveIntegerField(default=1, verbose_name='Build Version')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('source_file', models.FileField(upload_to=dictionary.models.dictionary_file_path, verbose_name='Source File')),
                ('html_file', models.FileField(blank=True, null=True, upload_to=dictionary.models.dictionary_file_path, verbose_name='HTML File')),
                ('opf_file', models.FileField(blank=True, null=True, upload_to=dictionary.models.dictionary_file_path, verbose_name='OPF File')),
                ('jpg_file', models.FileField(blank=True, null=True, upload_to=dictionary.models.dictionary_file_path, verbose_name='Cover Image')),
                ('mobi_file', models.FileField(blank=True, null=True, upload_to=dictionary.models.dictionary_file_path, verbose_name='MOBI File')),
                ('json_file', models.FileField(blank=True, null=True, upload_to=dictionary.models.dictionary_file_path, verbose_name='JSON Metadata')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to=dictionary.models.dictionary_file_path, verbose_name='ZIP Package')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('status_message', models.TextField(blank=True, verbose_name='Status Message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('built_at', models.DateTimeField(blank=True, null=True, verbose_name='Built At')),
            ],
            options={
                'verbose_name': 'Dictionary',
                'verbose_name_plural': 'Dictionaries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DictionarySuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content', models.TextField(blank=True, verbose_name='Dictionary Content')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='suggestions/', verbose_name='Source File')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Dictionary Suggestion',
                'verbose_name_plural': 'Dictionary Suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
