# Generated by Django 4.2.10 on 2025-03-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_create_dictionary_creator_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='Host SMTP')),
                ('port', models.PositiveIntegerField(default=25, verbose_name='Port SMTP')),
                ('encryption', models.CharField(choices=[('none', 'Brak'), ('ssl', 'SSL'), ('tls', 'TLS')], default='tls', max_length=10, verbose_name='Szyfrowanie')),
                ('auto_tls', models.BooleanField(default=True, verbose_name='Auto TLS')),
                ('authentication', models.BooleanField(default=True, verbose_name='Uwierzytelnianie')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Nazwa użytkownika SMTP')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='Hasło SMTP')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Zwrotny Adres e-mail')),
                ('from_name', models.CharField(max_length=255, verbose_name='Nazwa nadawcy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'verbose_name': 'Konfiguracja SMTP',
                'verbose_name_plural': 'Konfiguracje SMTP',
            },
        ),
    ]
