# Generated by Django 4.2.10 on 2025-03-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_smtpconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Opcjonalny adres e-mail, na który zostanie wysłane powiadomienie o utworzeniu słownika.', max_length=254, null=True, verbose_name='Adres e-mail do powiadomień'),
        ),
    ]
