# Generated by Django 4.2.10 on 2025-03-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_create_dictionary_edit_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='updater_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Updater Name'),
        ),
    ]
