# Generated by Django 4.2.10 on 2025-03-20 20:21

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_dictionary_updater_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Imię i nazwisko')),
                ('email', models.EmailField(blank=True, help_text='Opcjonalny adres e-mail, który zostanie użyty jako Reply-to w powiadomieniu.', max_length=254, verbose_name='Adres e-mail')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytana')),
            ],
            options={
                'verbose_name': 'Wiadomość kontaktowa',
                'verbose_name_plural': 'Wiadomości kontaktowe',
                'ordering': ['-created_at'],
            },
        ),
    ]
