# Generated by Django 4.2.10 on 2025-03-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('cloudflare', 'Cloudflare Turnstile'), ('google', 'Google reCAPTCHA')], default='cloudflare', max_length=20, verbose_name='Dostawca CAPTCHA')),
                ('site_key', models.CharField(max_length=255, verbose_name='Klucz witryny (Site Key)')),
                ('secret_key', models.CharField(max_length=255, verbose_name='Klucz tajny (Secret Key)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Włączone')),
                ('enable_login', models.BooleanField(default=True, verbose_name='Włącz dla logowania')),
                ('enable_contact', models.BooleanField(default=True, verbose_name='Włącz dla formularza kontaktowego')),
                ('enable_suggest', models.BooleanField(default=True, verbose_name='Włącz dla formularza propozycji słownika')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'verbose_name': 'Konfiguracja CAPTCHA',
                'verbose_name_plural': 'Konfiguracje CAPTCHA',
            },
        ),
    ]
