# Generated by Django 4.2.10 on 2025-03-21 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0009_captchaconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('task_type', models.CharField(choices=[('dictionary_suggestion', 'Sugestia słownika')], default='dictionary_suggestion', max_length=50, verbose_name='Typ zadania')),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('accepted', 'Zaakceptowane'), ('rejected', 'Odrzucone'), ('completed', 'Zrealizowane')], default='new', max_length=20, verbose_name='Status')),
                ('content', models.TextField(blank=True, verbose_name='Zawartość słownika')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='tasks/suggestions/', verbose_name='Plik źródłowy')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email zgłaszającego')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data realizacji')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Przypisane do')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Utworzone przez')),
                ('related_dictionary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tasks', to='dictionary.dictionary', verbose_name='Powiązany słownik')),
            ],
            options={
                'verbose_name': 'Zadanie',
                'verbose_name_plural': 'Zadania',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dictionarysuggestion',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictionary_suggestion', to='dictionary.task', verbose_name='Powiązane zadanie'),
        ),
    ]
