# Generated by Django 4.2.10 on 2025-03-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_dictionarysuggestion_author_name_task_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='original_content',
            field=models.TextField(blank=True, verbose_name='Oryginalna zawartość słownika'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('dictionary_suggestion', 'Sugestia słownika'), ('dictionary_change', 'Propozycja zmian w słowniku')], default='dictionary_suggestion', max_length=50, verbose_name='Typ zadania'),
        ),
    ]
