# Generated by Django 4.2.10 on 2025-03-24 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0013_task_original_content_alter_task_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_dictionary_notifications', models.BooleanField(default=True, help_text='Otrzymuj powiadomienia email o utworzeniu słownika.', verbose_name='Powiadomienia o utworzeniu słownika')),
                ('email_task_notifications', models.BooleanField(default=True, help_text='Otrzymuj powiadomienia email o nowych zadaniach i zmianach statusu zadań.', verbose_name='Powiadomienia o nowych zadaniach')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Ustawienia użytkownika',
                'verbose_name_plural': 'Ustawienia użytkowników',
            },
        ),
    ]
