# Generated by Django 5.2.15 on 2026-06-17 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_usersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='captchaconfiguration',
            name='enable_register',
            field=models.BooleanField(default=True, verbose_name='Włącz dla formularza rejestracji'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data akceptacji konta'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='Zaakceptowane przez'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Wysłano weryfikację emaila'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Token weryfikacji emaila'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Czy użytkownik kliknął link aktywacyjny wysłany na podany adres e-mail.', verbose_name='Email zweryfikowany'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Czy przy każdym logowaniu wymagać dodatkowego kodu wysyłanego e-mailem.', verbose_name='Email-2FA włączone'),
        ),
    ]
