# Generated by Django 5.2.15 on 2026-06-17 05:02

from django.db import migrations


def backfill_email_verified(apps, schema_editor):
    """Mark existing accounts as having a verified email + ensure each
    user has a UserSettings row.

    These users were created through the Django admin before the
    self-registration flow existed; they are trusted by definition and
    must not be locked out by the new "email confirmation required"
    gate. New users created from this migration onward will go through
    the regular registration → email verification → admin approval
    flow, which leaves email_verified=False until the link is clicked.
    """
    User = apps.get_model('auth', 'User')
    UserSettings = apps.get_model('dictionary', 'UserSettings')

    for user in User.objects.all():
        settings_row, _ = UserSettings.objects.get_or_create(user=user)
        if not settings_row.email_verified:
            settings_row.email_verified = True
            settings_row.save(update_fields=['email_verified', 'updated_at'])


def noop_reverse(apps, schema_editor):
    """Reversing the backfill would risk locking trusted users out; no-op."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0015_registration_fields'),
    ]

    operations = [
        migrations.RunPython(backfill_email_verified, noop_reverse),
    ]
